Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -38,14 +38,20 @@ workflows:
         script: keychain add-certificates
       - name: Increment build number
         script: |
-          cd $CM_BUILD_DIR/ios
-          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" || echo 0)
-          if [[ "$LATEST_BUILD_NUMBER" =~ ^[0-9]+$ ]]; then
-            NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
-            agvtool new-version -all $NEW_BUILD_NUMBER || { echo "Failed to set new build number"; exit 1; }
-          else
-            exit 1
-          fi
+        cd $CM_BUILD_DIR/ios
+        # Отримання останнього номеру збірки
+        LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" 2>/dev/null || echo 0)
+        
+        # Перевірка, чи є номер збірки числом
+        if [[ "$LATEST_BUILD_NUMBER" =~ ^[0-9]+$ ]]; then
+          # Інкрементуємо номер збірки
+          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
+          echo "Setting new build number: $NEW_BUILD_NUMBER"
+          agvtool new-version -all $NEW_BUILD_NUMBER || { echo "Failed to set new build number"; exit 1; }
+        else
+          echo "Failed to fetch latest build number or invalid build number: $LATEST_BUILD_NUMBER"
+          exit 1
+        fi
       - name: Set up code signing settings in Xcode project
         script: xcode-project use-profiles --warn-only
       - name: Build IPA for distribution
